config/routes.rb
Lvtc::Application.routes.draw do
  resources :race_registrations

  resources :announcements

  resources :newsletters

  resources :user_memberships

  resources :user_events

  resources :user_involvements

  resources :club_involvements

  resources :memberships

  resources :champion_series_points

  resources :grand_prix_points

  resources :users
  
  resources :charges

  resources :events

  get 'about', :to => 'welcome#about'
  get 'pdf_schedule', :to => 'pdf_schedule#pdf'
  get 'local_running_links', :to => 'welcome#running_links'
  get 'lvtc_membership', :to => 'welcome#lvtc_membership'
  get 'membership_type', :to => 'user_memberships#type'
  get 'membership_info', :to => 'user_memberships#info'
  get 'contact', :to => 'welcome#contact', :as => "contact"
  get 'champion_series_points_pdf', :to => 'welcome#champion_series_points_pdf', :as => "champion_series_points_pdf"

  get 'results/:id', :to => 'events#results', :as => "results"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'welcome#index'

  

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @announcement }
      else
        format.html { render action: 'new' }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params[:announcement]
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Listing announcements</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>