config/routes.rb
Lvtc::Application.routes.draw do
  resources :race_registrations

  resources :announcements

  resources :newsletters

  resources :user_memberships

  resources :user_events

  resources :user_involvements

  resources :club_involvements

  resources :memberships

  resources :champion_series_points

  resources :grand_prix_points

  resources :users
  
  resources :charges

  resources :events

  get 'about', :to => 'welcome#about'
  get 'pdf_schedule', :to => 'pdf_schedule#pdf'
  get 'local_running_links', :to => 'welcome#running_links'
  get 'lvtc_membership', :to => 'welcome#lvtc_membership'
  get 'membership_type', :to => 'user_memberships#type'
  get 'membership_info', :to => 'user_memberships#info'
  get 'contact', :to => 'welcome#contact', :as => "contact"
  get 'champion_series_points_pdf', :to => 'welcome#champion_series_points_pdf', :as => "champion_series_points_pdf"

  get 'results/:id', :to => 'events#results', :as => "results"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'welcome#index'

  

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/champion_series_point.rb
class ChampionSeriesPoint < ActiveRecord::Base
end

app/models/club_involvement.rb
class ClubInvolvement < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :race_registrations
	default_scope { order('date') }

	def self.future_events
		where('date >= ?', Date.today)
	end

	def self.past_events
		where('date < ?', Date.today).sort! { |a, b| b.date <=> a.date }
	end

	def formatted_price
	  sprintf("$%0.2f", self.price)
	end

	def stripe_price
		price * 100
	end

end

app/models/grand_prix_point.rb
class GrandPrixPoint < ActiveRecord::Base
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	has_many :user_memberships
	has_many :users, through: :user_memberships

	def stripe_price
		price * 100
	end

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/models/race_registration.rb
class RaceRegistration < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
	before_create :generate_confirmation_code

	private

	def generate_confirmation_code
  	self.confirmation_code = loop do
  		possible = (('A'..'Z').to_a + (0..9).to_a + ('a'..'z').to_a)
  		random_token = (0...6).map { |n| possible.sample }.join
  		break random_token unless RaceRegistration.where(confirmation_code: random_token).exists?
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :race_registrations
	belongs_to :user_membership
	belongs_to :membership
	before_create :assign_username

	def assign_username
		self.username = "#{first_name.downcase}#{last_name.downcase}"
	end

end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
end

app/models/user_involvement.rb
class UserInvolvement < ActiveRecord::Base
end

app/models/user_membership.rb
class UserMembership < ActiveRecord::Base
	has_many :users
	belongs_to :membership
	before_create :generate_membership_code

	private

	def generate_membership_code
  	self.membership_code = loop do
  		possible = (('A'..'Z').to_a + (0..9).to_a + ('a'..'z').to_a)
  		random_token = (0...6).map { |n| possible.sample }.join
  		break random_token unless UserMembership.where(membership_code: random_token).exists?
  	end
  end
end

app/controllers/race_registrations_controller.rb
class RaceRegistrationsController < ApplicationController
  before_action :set_race_registration, only: [:show, :edit, :update, :destroy]

  # GET /race_registrations
  # GET /race_registrations.json
  def index
    @race_registrations = RaceRegistration.all
  end

  # GET /race_registrations/1
  # GET /race_registrations/1.json
  def show
  end

  # GET /race_registrations/new
  def new
    @race_registration = RaceRegistration.new
    @event = Event.find(params[:event_id])
  end

  # GET /race_registrations/1/edit
  def edit
  end

  # POST /race_registrations
  # POST /race_registrations.json
  def create
    event = Event.find(params[:event_id])
    token = params[:stripeToken]
    firstname = params[:firstname]
    lastname = params[:lastname]
    email = params[:email]
    begin
      charge = Stripe::Charge.create(
        amount:      event.stripe_price,
        currency:    "usd",
        card:        token,
        description: "#{params[:firstname]} #{params[:lastname]},
                      #{event.title},
                      #{params[:email]}"
      )
      @registration = event.race_registrations.create!(
        event_id:   event.id,
        email:      params[:email]
        # fix
      )
      UserMailer.registration_confirmation(firstname, lastname, email, event).deliver
      redirect_to root_path
    rescue Stripe::CardError => e
      @error = e
      render :new
    end 
  end

  def update
    respond_to do |format|
      if @race_registration.update(race_registration_params)
        format.html { redirect_to @race_registration, notice: 'Race registration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @race_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /race_registrations/1
  # DELETE /race_registrations/1.json
  def destroy
    @race_registration.destroy
    respond_to do |format|
      format.html { redirect_to race_registrations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race_registration
      @race_registration = RaceRegistration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_registration_params
      params.require(:race_registration).permit(
      :event_id, :card_number, :card_code, :card_year, :card_month)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

	def current_admin
    current_user and current_user.admin
  end

  def current_admin?
    !!current_admin
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/race_registrations_helper.rb
module RaceRegistrationsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/race_registrations/_form.html.erb
<%= javascript_tag do %>
  window.stripePubKey = '<%= j Rails.configuration.stripe[:publishable_key] %>';
<% end %>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<h3>Register for <%= @event.title %></h3>
<% if @error %>
<%= @error %>
<% end %>

<div class="well" style="margin-left: 0px; position: relative; min-width: 510px; min-height: 180px;
height: auto">
  <%= form_tag race_registrations_path, :id => 'payment-form' do %>
    <%= hidden_field_tag :event_id, @event.id %>
    <table class="table">
  <thead>
    <th>Date</th>
    <th>Location</th>
    <th>Price</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @event.time %> on <%= @event.date.strftime('%a, %b %d') %></td>
      <td><%= @event.location %></td>
      <td><%= @event.formatted_price %></td>
    </tr>
  </tbody>
</table>
    <div class="row">
      <div style="float: left; padding-left: 25px">
        <label class="control-label" for="first-name">First Name</label>
        <input type="text" name="firstname" id="name" style="width: 20em"/>
￼￼￼   </div>
      <div style="float:left; padding-left: 25px">
        <label class="control-label" for="last-name">Last Name</label>
        <input type="text" size="20" name="lastname" id="name" style="width: 20em"/>
      </div>
      <div style="float: left; padding-left: 25px">
        <label class="control-label" for="email">Email</label>
        <input type="email" name="email" id="email" placeholder="you@example.com" style="width: 20em"/>
￼￼￼   </div>
      <div style="float: left; padding-left: 25px">
        <label class="control-label" for="number">Phone Number</label>
        <input type="text" name="number" id="number" placeholder="111-222-3456" style="width: 20em"/>
￼￼￼   </div>
    </div>

    <div class="row">
      <div style="float: left; padding-left: 25px">
        <label class="control-label" for="number">Card Number</label>
        <input type="text" size="20" data-stripe="number" id="number" placeholder="**** **** **** ****"
pattern="[\d ]*" style="width: 20em"/>
      </div>
      <div style="float: left; padding-left: 25px">
        <label class="control-label" for="cvc">CVC</label>
        <input type="text" style="width: 3em" size="3" data-stripe="cvc" id="cvc" placeholder="***"
pattern="\d*"/>
        <%= image_tag('credit.png', size:'40x40') %>
      </div>
      <div style="float: left; padding-left: 25px">
        <label class="control-label">Expiration Date</label>
        <input style="width: 2em" type="text" size="2" id="exp-month" data-stripe="exp-month"
placeholder="MM" pattern="\d*"/>
        <span> / </span>
        <input style="width: 3em" type="text" size="4" id="exp-year" data-stripe="exp-year" placeholder=
"YYYY" pattern="\d*"/>
      </div>
    </div>
    <div class="row" style="margin-top: 40px">
      <h6 style="padding:30px">By clicking the button below, I understand that my card will be charged <%= @event.formatted_price %> and I will be registered for <%= @event.title %>.</h6>
    <div class="text-center">
        <button type="submit" class="btn btn-primary btn-large">Register</button>
      </div>
    </div>
  <% end %>
</div>

app/views/race_registrations/edit.html.erb
<%- model_class = RaceRegistration -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/race_registrations/index.html.erb
<%- model_class = RaceRegistration -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:event_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @race_registrations.each do |race_registration| %>
      <tr>
        <td><%= link_to race_registration.id, race_registration_path(race_registration) %></td>
        <td><%= race_registration.user_id %></td>
        <td><%= race_registration.event_id %></td>
        <td><%=l race_registration.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_race_registration_path(race_registration), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      race_registration_path(race_registration),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_race_registration_path,
            :class => 'btn btn-primary' %>

app/views/race_registrations/new.html.erb
<%- model_class = RaceRegistration -%>
<div class="page-header">
  <h3></h3>
</div>
<%= render :partial => 'form' %>

app/views/race_registrations/show.html.erb
<%- model_class = RaceRegistration -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @race_registration.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_id) %>:</strong></dt>
  <dd><%= @race_registration.event_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              race_registrations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_race_registration_path(@race_registration), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              race_registration_path(@race_registration),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>