config/routes.rb
Lvtc::Application.routes.draw do
  resources :race_registrations

  resources :announcements

  resources :newsletters

  resources :user_memberships

  resources :user_events

  resources :user_involvements

  resources :club_involvements

  resources :memberships

  resources :champion_series_points

  resources :grand_prix_points

  resources :users
  
  resources :charges

  resources :events

  get 'about', :to => 'welcome#about'
  get 'pdf_schedule', :to => 'pdf_schedule#pdf'
  get 'local_running_links', :to => 'welcome#running_links'
  get 'lvtc_membership', :to => 'welcome#lvtc_membership'
  get 'membership_type', :to => 'user_memberships#type'
  get 'membership_info', :to => 'user_memberships#info'
  get 'contact', :to => 'welcome#contact', :as => "contact"
  get 'champion_series_points_pdf', :to => 'welcome#champion_series_points_pdf', :as => "champion_series_points_pdf"

  get 'results/:id', :to => 'events#results', :as => "results"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'welcome#index'

  

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/club_involvement.rb
class ClubInvolvement < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :race_registrations
	default_scope { order('date') }

	def self.future_events
		where('date >= ?', Date.today)
	end

	def self.past_events
		where('date < ?', Date.today).sort! { |a, b| b.date <=> a.date }
	end

	def formatted_price
	  sprintf("$%0.2f", self.price)
	end

	def stripe_price
		price * 100
	end

end

app/models/grand_prix_point.rb
class GrandPrixPoint < ActiveRecord::Base
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	has_many :user_memberships
	has_many :users, through: :user_memberships

	def stripe_price
		price * 100
	end

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/models/race_registration.rb
class RaceRegistration < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
	before_create :generate_confirmation_code

	private

	def generate_confirmation_code
  	self.confirmation_code = loop do
  		possible = (('A'..'Z').to_a + (0..9).to_a + ('a'..'z').to_a)
  		random_token = (0...6).map { |n| possible.sample }.join
  		break random_token unless RaceRegistration.where(confirmation_code: random_token).exists?
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :race_registrations
	belongs_to :user_membership
	belongs_to :membership
	before_create :assign_username

	def assign_username
		self.username = "#{first_name.downcase}#{last_name.downcase}"
	end

end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
end

app/models/user_involvement.rb
class UserInvolvement < ActiveRecord::Base
end

app/models/user_membership.rb
class UserMembership < ActiveRecord::Base
	has_many :users
	belongs_to :membership
	before_create :generate_membership_code

	private

	def generate_membership_code
  	self.membership_code = loop do
  		possible = (('A'..'Z').to_a + (0..9).to_a + ('a'..'z').to_a)
  		random_token = (0...6).map { |n| possible.sample }.join
  		break random_token unless UserMembership.where(membership_code: random_token).exists?
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@event = Event.where(:front_page => true).first
	end

	def about
	end

	def running_links
	end

	def lvtc_membership
	end

	def contact
	end

	def champion_series_points_pdf
	end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

	def current_admin
    current_user and current_user.admin
  end

  def current_admin?
    !!current_admin
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/welcome/about.html.erb
<h3>About Us</h3>

<img style="float:right;padding:5px" src='https://scontent-a-sjc.xx.fbcdn.net/hphotos-frc1/431283_10150588037645949_1409748653_n.jpg' height='350' width='350'>
<br>

<p>The Las Vegas Track Club is an all-volunteer, non-profit running organization that was incorporated in the state of Nevada in April, 1969. We are walkers, joggers and runners who have embraced walking, jogging and running as lifetime fitness activities. Our mission is to support youth running in southern Nevada, and we do that by making very generous donations to youth running teams and high school cross country and track teams, and by giving scholarships to worthy graduating high school seniors.</p>

<p>We work very closely with local charities who stage walking, jogging and running events to maintain a common calendar so that every event has a chance for success. We also stage our own running events when there is nothing else on the weekend calendar. We have over 1,000 members from 23 states, and we are always delighted to have new friends to walk, jog, and run with.</p>

<p>Our website has an extensive race calendar that features all local races and running events. If you want to race a 5K, 10K, half marathon, marathon, ultra distance, or track event, it will be listed on the LVTC race schedule. The calendar also has a large list of local training runs. The local running links page has links to local running clubs, bike and triathlon clubs, places to run, local government recreation, speciality running stores, race timing, and running companies. If you are interested in running a 5K, 10K, half marathon, marathon, ultra distance, track event or training run, please check out our running calendar.</p>

<p>LVTC events are open to all runners; sign up starts about a half hour before the race. The race fee is usually $3 for members, $5 for non-members. Students 19 and under receive a $1 discount. Almost all races are separated into sex and age categories, with ribbons awarded to the top five finishers in each division. In an effort to encourage young runners to join us, the LVTC does not charge for runners 10 years of age or younger.</p>
<br>

<h3>LVTC Contacts</h3>

<table class="table">
	<thead>
		<th>Name</th>
		<th>Position</th>
		<th>Email</th>
		<th>Phone</th>
	</thead>
	<tbody>
		<tr>
			<td>Tim Kelly</td>
			<td>President</td>
			<td></td>
			<td>(702) 882-3288</td>
		</tr>
		<tr>
			<td>James Alejandro</td>
			<td>1st Vice President</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>Betty Cook</td>
			<td>2nd Vice President</td>
			<td></td>
			<td>(702) 672-5525</td>
		</tr>
		<tr>
			<td>Werner Hellmuth</td>
			<td>3rd Vice President</td>
			<td></td>
			<td>(702) 735-3662</td>
		</tr>
		<tr>
			<td>Mike Reago</td>
			<td>Secretary</td>
			<td></td>
			<td>(702) 385-4717</td>
		</tr>
		<tr>
			<td>Ryan Young</td>
			<td>Ryan Young</td>
			<td></td>
			<td>(702) 526-1098</td>
		</tr>
		<tr>
			<td>Lee Beausoleil</td>
			<td>Membership Chair</td>
			<td></td>
			<td>(575) 218-5602</td>
		</tr>
		<tr>
			<td>Rachel Warbelow</td>
			<td>Events Schedule Chair</td>
			<td></td>
			<td>(812) 322-7607</td>
		</tr>
	</tbody>
</table>

app/views/welcome/champion_series_points_pdf.html.erb
<br><br>
<iframe src="http://www.lvtc.org/images/2013%20champ%20point%20standings.pdf" width="650px" height="830px"></iframe>

app/views/welcome/contact.html.erb
<h3>LVTC Contacts</h3>

<table>
	<thead>
		<th>Name</th>
		<th>Position</th>
		<th>Email</th>
		<th>Phone</th>
	</thead>
	<tbody>
		<tr>
			<td>Tim Kelly</td>
			<td>President</td>
			<td></td>
			<td>(702) 882-3288</td>
		</tr>
		<tr>
			<td>James Alejandro</td>
			<td>1st Vice President</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>Betty Cook</td>
			<td>2nd Vice President</td>
			<td></td>
			<td>(702) 672-5525</td>
		</tr>
		<tr>
			<td>Werner Hellmuth</td>
			<td>3rd Vice President</td>
			<td></td>
			<td>(702) 735-3662</td>
		</tr>
		<tr>
			<td>Mike Reago</td>
			<td>Secretary</td>
			<td></td>
			<td>(702) 385-4717</td>
		</tr>
		<tr>
			<td>Ryan Young</td>
			<td>Ryan Young</td>
			<td></td>
			<td>(702) 526-1098</td>
		</tr>
		<tr>
			<td>Lee Beausoleil</td>
			<td>Membership Chair</td>
			<td></td>
			<td>(575) 218-5602</td>
		</tr>
		<tr>
			<td>Rachel Warbelow</td>
			<td>Events Schedule Chair</td>
			<td></td>
			<td>(812) 322-7607</td>
		</tr>
	</tbody>
</table>

app/views/welcome/index.html.erb
<% if @announcement %>
	<div style="background-color:#FFFB7A;padding:10px">
		<h4><%= @announcement.title %></h4>
		<p><%= @announcement.line_1 %></p>
		<p><%= @announcement.line_2 %></p>
	</div>
<% end %>

<div class="well" style="margin-left: 0px; position: relative; min-width: 510px; min-height: 300px;height: auto;">
	<h3 class="text-info"><%= link_to @event.title, @event %></h3>
	<img src=<%= @event.front_page_photo_url %> height='320' width='320' style='margin:5px;float:right;border-radius:5px'>
	<blockquote><p><%= @event.date.strftime('%A, %B %e, %Y') %> at <%= @event.time %></p>
	<p><%= @event.location %></p></blockquote>
	
	<p><%= @event.description_1 %></p>
	 
	<p><%= @event.description_2 %></p>

	<p><%= @event.description_3 %></p>

</div>

app/views/welcome/lvtc_membership.html.erb
<p>The Las Vegas Track Club was incorporated in Nevada in April, 1969 and is still the only non-profit running organization in Southern Nevada. Our goal is to help our members, our visitors and guests enjoy running and walking as a lifetime fitness activity. Throughout the year we host youth scholarship fundraisers and other events to help support young runners from elementary school through high school. All profits from our events are given back to the community in the form of grants to area youth running teams, and as scholarships to local high school seniors. Today we have nearly 1200 positive, upbeat members of all ages and abilities who have made walking or running a part of their active lifestyle. We would be delighted to have you be a part of the fun.</p>
<br>


<div class='text-center'>
	<%= link_to "Join LVTC", membership_type_path, :class => 'btn btn-large btn-info' %>
	<%= link_to "Renew Membership", about_path, :class => 'btn btn-large btn-info' %>
</div>

app/views/welcome/running_links.html.erb
<h3>Links to Local Running Clubs</h3>
<p><%= link_to "Cedar City Running Club", 'http://cedarcityrunningclub.wordpress.com/' %></p>
<p><%= link_to "Gone Running 2 Meetup Group", 'http://www.meetup.com/gone-running2/' %></p>
<p><%= link_to "Havasu Hustlers Run Club", 'http://www.havasuhustlers.com/' %></p>
<p><%= link_to "Las Vegas Marathon 21 Club", 'http://www.lvm21.com/' %></p>
<p><%= link_to "Mesquitos on the Run - Mesquite", 'http://www.mesquitosontherun.com/' %></p>
<p><%= link_to "Ninja Endurance Racing", 'http://ninjaenduranceracing.com/' %></p>
<p><%= link_to "Sin City Road Runners", 'http://www.sincityroadrunners.com/' %></p>
<p><%= link_to "Southern Nevada Team In Training", 'http://www.teamintraining.org/snv/' %></p>
<p><%= link_to "St. George Utah Running Club", 'http://www.stgeorgerunningclub.com/' %></p>
<p><%= link_to "Summerlin Striders Running Club", 'http://www.facebook.com/SummerlinStriders' %></p>
<p><%= link_to "Team Challenge Crohns & Colitis SW Chapter Las Vegas", 'http://www.ccteamchallenge.org/Teams/southwest_las_vegas.htm' %></p>
<p><%= link_to "The Wild Bunch Running Meetup Group", 'http://www.meetup.com/wildbunchrunning/' %></p>
<p><%= link_to "Valley Striders", 'http://www.valleystriders.com/' %></p>