config/routes.rb
Lvtc::Application.routes.draw do
  resources :race_registrations

  resources :announcements

  resources :newsletters

  resources :user_memberships

  resources :user_events

  resources :user_involvements

  resources :club_involvements

  resources :memberships

  resources :champion_series_points

  resources :grand_prix_points

  resources :users
  
  resources :charges

  resources :events

  get 'about', :to => 'welcome#about'
  get 'pdf_schedule', :to => 'pdf_schedule#pdf'
  get 'local_running_links', :to => 'welcome#running_links'
  get 'lvtc_membership', :to => 'welcome#lvtc_membership'
  get 'membership_type', :to => 'user_memberships#type'
  get 'membership_info', :to => 'user_memberships#info'
  get 'contact', :to => 'welcome#contact', :as => "contact"
  get 'champion_series_points_pdf', :to => 'welcome#champion_series_points_pdf', :as => "champion_series_points_pdf"

  get 'results/:id', :to => 'events#results', :as => "results"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'welcome#index'

  

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/champion_series_point.rb
class ChampionSeriesPoint < ActiveRecord::Base
end

app/models/club_involvement.rb
class ClubInvolvement < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :race_registrations
	default_scope { order('date') }

	def self.future_events
		where('date >= ?', Date.today)
	end

	def self.past_events
		where('date < ?', Date.today).sort! { |a, b| b.date <=> a.date }
	end

	def formatted_price
	  sprintf("$%0.2f", self.price)
	end

	def stripe_price
		price * 100
	end

end

app/models/grand_prix_point.rb
class GrandPrixPoint < ActiveRecord::Base
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	has_many :user_memberships
	has_many :users, through: :user_memberships

	def stripe_price
		price * 100
	end

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/models/race_registration.rb
class RaceRegistration < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
	before_create :generate_confirmation_code

	private

	def generate_confirmation_code
  	self.confirmation_code = loop do
  		possible = (('A'..'Z').to_a + (0..9).to_a + ('a'..'z').to_a)
  		random_token = (0...6).map { |n| possible.sample }.join
  		break random_token unless RaceRegistration.where(confirmation_code: random_token).exists?
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :race_registrations
	belongs_to :user_membership
	belongs_to :membership
	before_create :assign_username

	def assign_username
		self.username = "#{first_name.downcase}#{last_name.downcase}"
	end

end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
end

app/models/user_involvement.rb
class UserInvolvement < ActiveRecord::Base
end

app/models/user_membership.rb
class UserMembership < ActiveRecord::Base
	has_many :users
	belongs_to :membership
	before_create :generate_membership_code

	private

	def generate_membership_code
  	self.membership_code = loop do
  		possible = (('A'..'Z').to_a + (0..9).to_a + ('a'..'z').to_a)
  		random_token = (0...6).map { |n| possible.sample }.join
  		break random_token unless UserMembership.where(membership_code: random_token).exists?
  	end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => params[:price],
	    :description => "Bagel purchase",
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.past_events
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def results
    @event = Event.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :photo_url, :results_url, :time, :title, :website, :location, :contact_name, :comments, :grand_prix_points, :championship_series_points)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

	def current_admin
    current_user and current_user.admin
  end

  def current_admin?
    !!current_admin
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date, :id => 'datepick', :placeholder => "YYYY-MM-DD" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :time, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :time, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :results_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :results_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :grand_prix_points, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :grand_prix_points, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description_1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description_1, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description_2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description_2, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description_3, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description_3, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Front Page?", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :front_page, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "URL for Front Page Photo", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :front_page_photo_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contact_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contact_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comments, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :comments, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<h3>Results and Photos from Past Events</h3>
<% if current_admin? %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
              new_event_path,
              :class => 'btn btn-primary' %>
              <% end %>
              <br> <br>

<table class="table table-hover">
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <% if current_admin? %>
          <td><%= link_to event.id, event_path(event) %></td>
        <% end %>
        <td><%= link_to event.title, event %></td>
        <td><%= event.date.strftime('%m/%d/%Y') %></td>
        <% if event.results_url.present? %>
          <% if event.results_url[0..3] == "http" %>
            <td><%= link_to "View results", event.results_url %></td>
          <% else %>
            <td><%= link_to "View results", results_path(event) %></td>
          <% end %>
        <% else %>
          <td></td>
        <% end %>
        <% if event.photo_url.present? %>
          <td><%= link_to "View pictures", event.photo_url %></td>
        <% else %>
          <td></td>
        <% end %>
        <% if current_admin? %>
        <td>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/results.html.erb
<% if @event.results_url.empty? %>
	<h2><%= @event.title %></h2>
	<h4>No results have been posted yet.</h4>
<% else %>
<br>
	<iframe src="https://docs.google.com/viewer?srcid=<%= @event.results_url %>&pid=explorer&efh=false&a=v&chrome=false&embedded=true" width="650px" height="830px"></iframe>
<% end %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h3><%=t '.title', :default => @event.title %></h3>

  <% if @event.allow_registration %>
    <%= form_tag new_race_registration_path, method: :get do |f| %>
      <%= hidden_field_tag :event_id, @event.id %>
      <%= submit_tag "Register Online", :class => 'btn btn-success'  %>
      <% end %>
  <% end %>
  <%= link_to raw('<i class="icon-facebook"> &nbsp;|&nbsp; Share on Facebook</i>'), 
            "https://www.facebook.com/dialog/feed?
            app_id=#{ENV['FACEBOOK_APP_ID']}
            &picture=http://las-vegas-track-club.herokuapp.com/assets/new_logo-b15914286fbc615914da16b7cf080ab7.png
            &link=http://localhost:3000/events/#{@event.id}
            &display=popup&name=#{@event.title}
            &description=#{@event.location}%20at%20#{@event.time}%20on%20#{@event.date}
            &redirect_uri=http://localhost:3000/events/#{@event.id}", :class => 'btn btn-primary'%>
</div>
<p><strong>Date</strong>: <%= @event.date.strftime('%A, %B %e, %Y') %></p>
<p><strong>Time</strong>: <%= @event.time %></p>
<p><strong>Location</strong>: <%= @event.location %></p>
<p><strong>Website</strong>: <%= link_to @event.website, @event.website %></p>
<% if @event.price.present? %>
  <p><strong>Price</strong>: $<%= @event.price %></p>
<% end %>
<% if @event.comments.present? %>
  <p><strong>Comments</strong>: <%= @event.comments %></p>
<% end %>
<% if @event.grand_prix_points %>
  <p><strong>Grand Prix Points</strong>: <%= @event.grand_prix_points %></p>
<% end %>
<% if @event.results_url.present? %>
  <% if @event.results_url[0..3] == "http" %>
    <p><strong>Results</strong>: <%= link_to "View", @event.results_url %></p>
  <% else %>
    <p><strong>Results</strong>: <%= link_to "View", results_path(@event) %></p>
  <% end %>
<% end %>
<% if @event.photo_url.present? %>
  <p><strong>Photos</strong>: <%= link_to "View", @event.photo_url %></p>
<% end %>


<p><%= @event.description_1 %></p>
<p><%= @event.description_2 %></p>
<p><%= @event.description_3 %></p>

<% if current_admin? %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<% end %>